baseURL = "https://alinpanaitiu.com/"
env = "production"
languageCode = "en-us"
title = "Alin Panaitiu - Personal website"
theme = "blogophonic"
subtitle = "Developer, Designer"

description = "Alin Panaitiu's personal website"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
googleAnalytics = ""
disqusShortname = ""
metaDataFormat = "yaml"
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
# see more styles https://help.farbox.com/pygments.html
pygmentsStyle = "fruity"
pygmentsUseClasses = true
footnoteReturnLinkContents = "&#8617;" # ↩
# set deliberately low for testing choose your preffered number based on the blog layout you've chosen
paginate = 10
preserveTaxonomyNames = true

[author]
email = "alin@panaitiu.com"
name = "Alin Panaitiu"

[params]
  orgName = "Alin Panaitiu"
  orgLocal = "Brasov, Romania"
  favicon = "/favicon.ico?v=0"
  logo = "icons/logo.svg"
  textFontFamily = "sans-serif"
  headingFontFamily = "sans-serif"
  siteBgColor = "washed-gold"
  sidebarBgColor = "white-40"
  headlineColor = "dark-mauve"
  headingColor = "dark-mauve"
  textColor = "dark-gray"
  sidebarTextColor = "mid-gray"
  bodyLinkColor = "red"
  navLinkColor = "near-black"
  sidebarLinkColor = "red"
  footerTextColor = "silver"
  buttonTextColor = "near-white"
  buttonBgColor = "black"
  buttonHoverTextColor = "white"
  buttonHoverBgColor = "blue"
  borderColor = "dark-mauve"
  socialInHeader = false
  socialInFooter = false
  imgSizesMedium = [1920, 1280, 1024, 768, 640, 320]
  imgSizesMediumStr = "1920,1280,1024,768,640,320"
  imgSizes = [8120, 5260, 3840, 2560, 1920, 1200, 992, 768, 576, 320, 64]
  imgSizesStr = "8120,5260,3840,2560,1920,1200,992,768,576,320,64"
  mainSections = ["blog", "docs"]

[social]
  facebook = ""
  facebook_admin = "" # Facebook Page Admin ID for Domain Insights
  instagram = ""
  youtube = ""
  twitter = "alinp32"
  github = "alin23"
  medium = ""

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[privacy.youtube]
  privacyEnhanced = true